### ISSUE TITLE
Discovered a defect of this kind

### ISSUE THREAD

**Issue by Vladosetskii** [Vladosetskii/supreme-winner-the-KOBAN#1]
#include <stdio.h>

using namespace std;
class troad 
{
public:
int Width;
float Length;
troad();
troad(float Length0,int Width0);
void fileinput();
};
troad:: troad()
{
Length=0.0;
Width=0;
}
troad:: troad(float Length0,int Width0)
{
if (Length0>0)
Length = Length0;
else Length = 1;
if (Width0>0)
Width = Width0;
else Width = 1;
}
void troad::fileinput()
{
char buff[50];
char buff1[50];
ifstream fin ("popka.txt");
fin>>buff; Length=atof(buff);
fin>>buff1; Width=atoi(buff1);
}
int main()
{
troad road;
std::cout<<"road.Length = "<< road.Length<<"\nroad.Width = "<<road.Width<<std::endl;
road.fileinput();
std::cout<<"road.Length = "<< road.Length<<"\nroad.Width = "<<road.Width<<std::endl;
return 0;
}
![default](https://user-images.githubusercontent.com/46804364/51688877-87b21b80-2006-11e9-827b-0b1d7d081c99.jpg)

**Comment by Vladosetskii** [comment]
Я решил эту проблему спс всем кто помогал
![default](https://user-images.githubusercontent.com/46804364/51689302-70bff900-2007-11e9-98f1-7f1b4dcb6172.png)

**Comment by outerVoid** [comment]
точно решил?:DDD

**Comment by Vladosetskii** [comment]
У мамы спроси она знает
